

import { Suspense } from "react";
import "./globals.css";
import { Loading } from "./components/Loading";
import { AuthProvider } from './context/AuthContext';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </AuthProvider>
      </body>
    </html>
  );
}
